---
title: Br Richard.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  tooltips:
    title: Tooltips
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    comments: true
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    layout: page
    comments: true
    search: true
    tooltip: true
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    search: true
    sidebar: home_sidebar
    topnav: topnav
repository: br-richard/br-richard.github.io
output: web
topnav_title: Betriebsrat Dr. Richard
site_title: Betriebsrat Dr. Richard
company_name: Betriebsrat Dr. Richard
github_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
google_analytics: UA-66296557-1
host: 127.0.0.1
port: 4000
exclude:
- ".idea/"
- ".gitignore"
feedback_subject_line: Jekyll documentation theme
feedback_email: ferd.schilling@aon.at
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
sidebars:
- admin_sidebar
description: Homepage der Betriebsräte aller Dr. Richard Betriebe und des Konzernbetriebsrates.
url: https://br-richard.github.io
